# version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    #   - jekyll_bundle_cache:/app/vendor/bundle
    # La sezione 'environment' deve essere un mapping YAML.
    # Se non hai variabili d'ambiente da definire, puoi commentare anche la riga 'environment:'
    # Oppure puoi lasciarla vuota come nell'esempio qui sotto.
    # environment:
      # BASE_PATH: "/il-tuo-repository" # Lasciala commentata così, con l'indentazione corretta.
      # Se la decommenti, assicurati che sia "chiave: valore"
      # Esempio:
      # JEKYLL_ENV: development
    stdin_open: true
    tty: true

# volumes:
#   jekyll_bundle_cache: